  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest
  
  - name: start and enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: run app pre-requisites
    ansible.builtin.import_role:  # this cmd wil import code from common folder
      name: common
      tasks_from: app-pre-req  #here we r loading tasks from common , vars also automaticaly wil run

  - name: copy backend conf  # here we done some changes so do restart nginx
    ansible.builtin.template:
      src: expense.config.j2
      dest: /etc/nginx/default.d/expense.config
    notify:  # handlers are notifiers
    - restart nginx

  # - name: restart nginx   # if there r any changes in config 
  #   ansible.builtin.service:
  #     name: nginx
  #     state: restarted